### ISSUE TITLE
Nii2mnc Requires Uncompressed Inputs

### ISSUE THREAD

**Issue by crocodoyle** [aces/cbrain-plugins-neuro#137]
`nii2mnc` tasks launched with compressed inputs fail on cluster, and the error log doesn't give a helpful error message, just that the expected .mnc file is not there

Please update the `nii2mnc` tool to automatically uncompress compatible inputs (like every other program in existence) and give more detailed error messages.

**Comment by prioux** [comment]
This was done today.

https://github.com/aces/cbrain-plugins-neuro/commit/20ee27e3c7455d4241689b29972c1fe8a2199b8e
