### ISSUE TITLE
BEst Spark taging

### ISSUE THREAD

**Issue by MontrealSergiy** [aces/cbrain-plugins-neuro#167]
BEst and Spark lack eeg and fmri labels respectively

**Comment by MontrealSergiy** [comment]
![image](https://user-images.githubusercontent.com/11949081/98761832-45f19100-23a4-11eb-97f6-bbb82e51d18f.png)

**Comment by prioux** [comment]
Tags are configured by admin.

This issue is not about the platform, so closing.
