### ISSUE TITLE
The "FslMelodic Output" viewer code is all broken.

### ISSUE THREAD

**Issue by prioux** [aces/cbrain-plugins-neuro#2]
When rendering userfiles of that type, the view code contains full paths on the cluster sides for rendering the images, so it's all borken. See screenshot.

![screen shot 2015-12-16 at 17 02 56](https://cloud.githubusercontent.com/assets/777588/11855279/3fb763ee-a417-11e5-843a-cbd9ce83e668.png)

The image's SRC URL in the HTML is all weird:

```
577603/content?arguments=melodic-output-305651-3.gica//nfs3_ib/evans-ms.nfs/tank/nfs/evans/nobackup/share/prioux/gridshare/30/56/51/asimioni-FslMelodic-T305651/denoised_func_data_nonaggr_run1_s06202.nii_melodic-output-305651-3.ica/reg/example_func2standard1.png&amp;content_loader=collection_file&amp;content_viewer=off&amp;viewer=image_file&amp;viewer_userfile_class=ImageFile
```

**Comment by glatard** [comment]
The full paths that show in the HTML page will stay: this is how the page is generated by FSL. I'm not sure about the SRC URL, can you share the melodic output file with me?

**Comment by glatard** [comment]
Completely re-generated these pages (discarded whatever FSL was creating).
