### ISSUE TITLE
Add brainstem processing in ReconAll

### ISSUE THREAD

**Issue by prioux** [aces/cbrain-plugins-neuro#209]
It seems this has been put into a separate script. ReconAll produces this message when invoked with `-brainstem-structures` :

```
ERROR: the brainstem module is now a separate script: segmentBS.sh
 
For help, please execute the script with the flag --help: 
 
     segmentBS.sh --help
 
or visit the following page: 
 
https://surfer.nmr.mgh.harvard.edu/fswiki/BrainstemSubstructures
 ```

**Comment by prioux** [comment]
The current container seems to be missing some matlab stuff too:

```
Singularity> segmentBS.sh --help
     
ERROR: cannot find Matlab 2014b runtime in location:
     
/usr/local/freesurfer/MCRv84
     
It is looking for either: 
  bin/glnxa64/libmwlaunchermain.so    (Linux 64b) or
  bin/maci64/libmwlaunchermain.dylib (Mac 64b)
 
The hippocampal/amygdala and brainstem modules require the (free) Matlab runtime.
You will need to download the Matlab Compiler Runtime (MCR) for Matlab 2014b.
To do so, please run the following command (you might need root permissions):
 
fs_install_mcr R2014b
 
For further details, please visit https://surfer.nmr.mgh.harvard.edu/fswiki/MatlabRuntime
```

**Comment by StongeEtienne** [comment]
Hi @prioux,
Thanks for creating this issue.

On my computer I was able to install it by running (after FS install) :
`fs_install_mcr R2014b`

and installing some missing package :
`sudo apt-get install libncurses5
sudo apt-get install tcsh`

**Comment by natacha-beck** [comment]
@prioux It is done, no ? Could we closed ?

**Comment by prioux** [comment]
Yes, the brainstem module is now supported in the FreesurfeReconAll 7.2.0 as integrated with the new integrator.

The initial commit was https://github.com/aces/cbrain-plugins-neuro/commit/a0c484abf3f2e742d780367fbf2da5619b87a66a

Since then, the amygdala segmentation module was also added in commit

https://github.com/aces/cbrain-plugins-neuro/commit/dc3df255ddf564c5074be206372a68d29b21e2e3

I'm not planning to retrofit these modules in older versions of ReconAll.
