### ISSUE TITLE
FSL Melodic: Option to change the standard space not functional

### ISSUE THREAD

**Issue by Najmahan** [aces/cbrain-plugins-neuro#22]
In CBRAIN-MELODIC interface, user may chose to "Use custom template file", however there is no way for user to choose this template file.

It can be provided as an option to select a template file together with the CSV and FSF file before launching melodic.

Preferably, this could be added as the 4th column in the CSV file.

**Comment by glatard** [comment]
Yes, it is possible to choose a template file. Template files have to be tagged with tag "template". They will then show in a drop-down list.

**Comment by Najmahan** [comment]
It is not clear how to do this.

I have tried to tag a file as template by going to File -> More -> tags  and then typed "template" because template was not a default on the drop down menu. However, this did not change the "tag" of the file. This did not show any template file in the task parameter interface.

I also tried to change the file Type to template, but there is no template type in the drown list.

**Comment by glatard** [comment]
Files are tagged through the More -> Properties menu. More -> Tags is to create/delete tags. When a file is properly tagged as "template", then it shows in the drop-down menu.

**Comment by prioux** [comment]
Yes, basically, you have to **create** a tag before you can assign it.

**Comment by Najmahan** [comment]
That is what I did, through the tag menu.

Except that the file doesn't seem to get "tagged".

**Comment by glatard** [comment]
To assign the tag you have to use the Properties menu.

**Comment by Najmahan** [comment]
Thanks.

I see that the "more" option can be confusing in a sense that the first
part (filters/tags) is about creating general tags; then in the lower
section its things that can be done on files and etc.

A little pop-up help on the "more" options can help. I will document this.

**Comment by remibernard** [comment]
@Najmahan You are right; for someone who wishes to edit a file's tags, the tags menu seems like the first thing to try :(. Unfortunately I'm not sure how the situation could be improved; do you have an idea on how the menu could be designed to avoid this issue?

@prioux AFAIK you should be able to just enter a new tag name in the properties dialog. This feature is one of the highlights of the new interface.
