### ISSUE TITLE
Updating boutiques descriptor and container for hippunfold v1.1.0?

### ISSUE THREAD

**Issue by akhanf** [aces/cbrain-plugins-neuro#238]
Hello,

We have a new version of hippunfold v1.1.0, hoping to have this added to CBRAIN too? There are a few command-line changes since v1.0.0, so the boutiques would need to be altered slightly too. Let me know if I can help, the updated API is here: https://hippunfold.readthedocs.io/en/latest/usage/app_cli.html

Thanks,
Ali

**Comment by prioux** [comment]
Sure, Natacha is on vacation until August, but I'll mention this at the next CBRAIN dev meeting and see who can do the work.

**Comment by prioux** [comment]
I'm trying to figure out which (if any) command-line options have changed between 1.0.0 and 1.1.0 .

Are there any?

**Comment by prioux** [comment]
When grepping through the JSON file, I see that currently for 1.0.0 the following options are implemented:

```json
        "command-line-flag": "--modality"
        "command-line-flag": "--derivatives"
        "command-line-flag": "--skip_preproc" 
        "command-line-flag": "--skip_coreg"
        "command-line-flag": "--skip_inject_template_labels" 
        "command-line-flag": "--inject-template-smoothing-factor" 
        "command-line-flag": "--rigid_reg_template" 
        "command-line-flag": "--no_reg_template" 
        "command-line-flag": "--template" 
        "command-line-flag": "--t1_reg_template" 
        "command-line-flag": "--nnunet_disable_tta" 
        "command-line-flag": "--output_spaces",
        "command-line-flag": "--output_density",
        "command-line-flag": "--hemi",
        "command-line-flag": "--laminar_coords_method",
        "command-line-flag": "--keep_work" 
        "command-line-flag": "--force-nnunet-model",
```

I don't know if all the other options in the new documentation are truly new or they simply were not meant to be integrated in CBRAIN.

For the moment @akhanf I can deploy the container for v1.1.0 using the current set of options as specified in v1.0.0. Is that sufficient? (I'm assuming it's backwards compatible)

**Comment by MontrealSergiy** [comment]
at least one flag is renamed, https://github.com/khanlab/hippunfold/releases

**Comment by akhanf** [comment]
One backwards incompatible change is:
The `--nnunet_disable_tta` option is replaced with the `--nnunet_enable_tta` option, and the default for this is now `False`.

The new options that we should include are `--atlas` and `--generate-myelin-map`. The possible values can be found in the documentation.

Everything else should be fine as is.

**Comment by prioux** [comment]
Alright, thanks for the info, I think I can do all that!

**Comment by prioux** [comment]
I push the new descriptor, I'll now pull the container and configure/deploy it.

**Comment by akhanf** [comment]
Excellent thank you!

**Comment by akhanf** [comment]
Hello,

One of the users of the app has been having some issues and I am wondering if they may be related to CPU/memory resources for the submitted job. It seems like 1 CPU is granted to the job on cbrain, and not sure how much memory. Is there any way this can be increased? We use 8cores/32GB normally when we run the jobs on graham.

Ali

**Comment by prioux** [comment]
It's possible. It's an easy problem to fix an investigate for us, but given there are > 300 Hippunfolds that were run just this month (some OK, some failed), we'd like to be given the task ID so we can have a look.

Normally this type of support request is not done on GitHub (we use github for tracking code changes only). But all CBRAIN users have free access to a support forum: https://forum.cbrain.mcgill.ca (once authenticated with CBRAIN first). That's the perfect place to report such a problem. Can the user having difficulty create a post there please? Just a one line sentence and a link to the failed task is enough.

**Comment by akhanf** [comment]
Sure no problem, I only tried here first in case it was an app set-up issue. I'll pass this on to the user (they are already on the forum).

**Comment by prioux** [comment]
Perfect, thanks! Just a heads up, the forum is being upgraded with the latest patches as I write this right now, so it is possible it will be unavailable for a few minutes this morning.
