### ISSUE TITLE
Enable the grouping of Melodic results in a MelodicStudy

### ISSUE THREAD

**Issue by glatard** [aces/cbrain-plugins-neuro#38]
Melodic results should be grouped in a "MelodicStudy" when user selects option in launch form (defaults to yes). Launching melodic should launch a new task that will wait for the others to complete and then group the results. Replicate what is done in CivetCombiner.

**Comment by prioux** [comment]
CivetCombiner is a bad model to base your code! I know, I'm the one who coded it!

The way I see it, for CIVET, I should have created the study model to be "virtual". It doesn't have to include in its content the
whole CivetOutputs, it just needs to be able to refer to them and provide some methods to access them virtually. In fact I have
an issue in GitHub to do just that.

**Comment by glatard** [comment]
Abandoned after discussion with @Najmahan
