### ISSUE TITLE
FSL Melodic: add a disclaimer about "post stats and time series" in the documentation

### ISSUE THREAD

**Issue by glatard** [aces/cbrain-plugins-neuro#39]

**Comment by Najmahan** [comment]
done!

**Comment by crocodoyle** [comment]
Is this still in need of fixing? Where is the documentation?

**Comment by Najmahan** [comment]
The logic of accepting input-data in MELODIC and ICA-AROMA needs to be
harmonized. I suggest we meet with Tristan (AA & G) and discuss adapting
melodic to accept data in the same way as ICA-AROMA.

The documentation for melodic is currently here:
https://docs.google.com/presentation/d/1YlVAmOkpRHaqPaqvXXbcU2uuuDZjwnq3k893CGB5GTE/edit#slide=id.g10dd3d2dae_1_5

N.

**Comment by glatard** [comment]
The initial issue has been fixed indeed. What @Najmahan mentions will be solved when/if Melodic is implemented as a Boutiques task (see https://github.com/aces/cbrain-plugins-neuro/issues/3).
