### ISSUE TITLE
Update MincBet, fsl_anat and ICA-AROMA using the latest Boutiques features

### ISSUE THREAD

**Issue by glatard** [aces/cbrain-plugins-neuro#57]
Non exhaustive list:
* Add parameter groups wherever relevant.
* Add mutual exclusion between input file and input dir in FSL anat.
* Add one of a set requirement between input files in ICA AROMA.

Following @Najmahan comment, it would also be useful to add the type of files that need to be selected to the description of these tools (e.g., for MINCBet "This tool processes a MINC file." or for FSL anat "This tool processes a NIFTI file *or* a .anat directory"). 

@ttaa9 I cannot assign this issue to you until you accept the invitation to the repo, but it is for you :)

**Comment by Najmahan** [comment]
Yes, expected inputs and expected outputs should be explained.

**Comment by natacha-beck** [comment]
@ttaa9 This one can be close ? no ?

**Comment by glatard** [comment]
yes, it can.
