### ISSUE TITLE
Restrict BET options for fMRI data

### ISSUE THREAD

**Issue by glatard** [aces/cbrain-plugins-neuro#6]
BET can run on 4D fMRI data by selecting option -F. If this option is selected, other ones, such as -B, -S, -R must become unwritable. Otherwise, the output will be seriously erroneous, and only one volume.

Was issue #27 in cbrain-plugins-fsl

**Comment by glatard** [comment]
Could be done while doing #11.

**Comment by crocodoyle** [comment]
Can be closed

**Comment by prioux** [comment]
@glatard Plase close if this is done. I can't tell.

**Comment by glatard** [comment]
Yes it's done in #61 (see input groups with `mutually-exclusive` property).
